name: Build extension

on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master', 'dev']

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Check code format and issues
        run: |
          npm install
          npm run check

  build:
    needs: check

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ['chrome', 'firefox']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Build
        run: |
          npm install
          npm run build:${{matrix.browser}}

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jira-issue-expert
          path: |
            dist/**/*.zip
          if-no-files-found: error
